/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Example } from "./Example";
export * as factories from "./factories";
export { Example__factory } from "./factories/Example__factory";
