import { ConnectWallet } from "components/ConnectWallet";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Wagmi Dapp</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <ConnectWallet></ConnectWallet>
            </div>
        </div>
    );
};

export default Home;
